version: '3.4'

volumes:
  rfp_datafiles: 

services:
  rfpportal_db:
    image: mysql:5.7
    volumes:
      - rfp_datafiles:/var/lib/mysql      
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Fidelio06
      - MYSQL_DATABASE=daorfpdb
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=Fidelio06 --execute \"SHOW DATABASES;\"" #["CMD", 'mysqladmin', 'ping', '-h', 'localhost:3317', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 20s
      retries: 10
    networks:
      - rfpnetwork

  rfpportalwebsite:
    image: ${DOCKER_REGISTRY-}rfpportalwebsite
    build:
      context: .
      dockerfile: RFPPortalWebsite/Dockerfile
    depends_on:
      rfpportal_db:
        condition: service_healthy
    networks:
     - rfpnetwork

networks:
  rfpnetwork:
    name: rfpnetwork
    driver: bridge

