version: '3.4'

services:
  rfpportalwebsite:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 
    ports:
      - "6080:80"
  rfpportal_db: 
    ports:
      - 3317:3306

